import fs from 'node:fs';
import path from 'node:path';

import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

import { PLAY_STORE_URL } from './src/constants';

/**
 * Every screenshot in `static/img/guide/`, without the extension.
 *
 * The swizzled `src/theme/MDXComponents/Img` needs two things this answers.
 * It has to recognise a guide screenshot at all - by the time it runs, the
 * `/img/guide/vault-list.webp` written in the Markdown has become a hashed
 * `/assets/images/...` URL - and it has to know which screens were shot in
 * both app themes: `<name>.webp` is the dark one, `<name>-light.webp` is the
 * same screen in light, and it swaps between them with the site theme.
 *
 * Read from disk rather than kept by hand, so adding a light shot is a file
 * drop and the Markdown never mentions a theme.
 */
const guideShots = fs
  .readdirSync(path.join(__dirname, 'static', 'img', 'guide'))
  .filter((name) => name.endsWith('.webp'))
  .map((name) => name.replace(/\.webp$/, ''));

/**
 * Site config for passwordepic.com.
 *
 * Two settings here are load-bearing rather than cosmetic:
 *
 *  - `url` + `baseUrl` must match the custom domain exactly. The app links to
 *    `https://passwordepic.com/privacy`, and Google Play fetches that URL when
 *    reviewing the listing — a wrong baseUrl turns it into a 404 and the
 *    submission is rejected.
 *  - `onBrokenLinks: 'throw'` keeps the build honest. This site documents a
 *    product whose security claims must stay exact; a dead link to the page
 *    that qualifies a claim is how the unqualified version survives.
 */
const config: Config = {
  title: 'PasswordEpic',
  tagline: 'A password manager that cannot read your passwords',
  favicon: 'img/favicon.ico',

  url: 'https://passwordepic.com',
  baseUrl: '/',

  organizationName: 'TuPhung369',
  projectName: 'passwordepic-website',
  // Emits `privacy/index.html` rather than a flat `privacy.html`.
  //
  // Directory-with-index is the one layout every static host serves the same
  // way. The flat form relies on the host guessing an `.html` extension, and
  // `/privacy` is the URL Google Play fetches when reviewing the listing - not
  // somewhere to depend on host-specific behaviour.
  trailingSlash: true,

  onBrokenLinks: 'throw',
  // Diagrams. The docs explain a key split across four places and a handful of
  // decision trees ("autofill is not appearing", "I am getting a new phone"),
  // and those land far better as a picture than as three paragraphs.
  themes: ['@docusaurus/theme-mermaid'],
  // The FAQ links into specific sections of the setup guide. A broken anchor
  // does not 404 - it silently drops the reader at the top of a long page,
  // which is exactly the failure this site cannot afford in troubleshooting
  // steps. Same reasoning as onBrokenLinks above.
  onBrokenAnchors: 'throw',

  // Docusaurus emits `favicon` only; iOS wants its own tag when a visitor adds
  // the site to their home screen.
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'apple-touch-icon',
        sizes: '180x180',
        href: '/img/apple-touch-icon.png',
      },
    },
  ],
  markdown: {
    mermaid: true,
    // Top-level `onBrokenMarkdownLinks` is deprecated and removed in v4.
    hooks: { onBrokenMarkdownLinks: 'warn' },
  },

  customFields: { guideShots },

  // Adding a language = add the code here, then drop translated Markdown into
  // `i18n/<code>/`. Untranslated strings fall back to English rather than
  // breaking the build, so a locale can ship before it is complete.
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'vi'],
    localeConfigs: {
      en: { label: 'English', htmlLang: 'en-US' },
      vi: { label: 'Tiếng Việt', htmlLang: 'vi-VN' },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          // No sidebar. The navbar is the only chrome on this site: docs get
          // the full width, and the floating star in src/components/StarToc
          // replaces the right-hand table of contents. Navigation between doc
          // pages lives in the navbar dropdown below.
          sidebarPath: false,
          routeBasePath: 'docs',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // `neutral` reads as a drawing rather than as a developer tool, which is
    // the point - these diagrams are for readers deciding whether to trust the
    // product, not for engineers reviewing an architecture.
    mermaid: {
      theme: { light: 'neutral', dark: 'dark' },
      options: { flowchart: { curve: 'basis', useMaxWidth: true } },
    },
    // Open Graph card. Must be a raster image - no crawler renders SVG, so
    // the previous `logo.svg` here meant every shared link showed no preview
    // at all. Generated by scripts/build-brand-assets.py.
    image: 'img/social-card.png',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'PasswordEpic',
      logo: { alt: 'PasswordEpic', src: 'img/logo.png' },
      hideOnScroll: false,
      items: [
        // Two dropdowns rather than one: "how do I use it" and "how does it
        // work" are different visits, and a single twelve-item list served
        // neither.
        {
          type: 'dropdown',
          label: 'User guide',
          position: 'left',
          items: [
            { to: '/docs/guide-vault', label: 'Your vault' },
            { to: '/docs/guide-generator', label: 'Generating passwords' },
            { to: '/docs/guide-settings', label: 'Settings' },
            { to: '/docs/autofill', label: 'Setting up autofill' },
            { to: '/docs/your-passcode', label: 'Your passcode' },
            { to: '/docs/faq', label: 'Common problems' },
          ],
        },
        {
          type: 'dropdown',
          label: 'How it works',
          position: 'left',
          items: [
            { to: '/docs/how-it-works', label: 'The key, and where it lives' },
            { to: '/docs/attack-scenarios', label: 'The war for the vault' },
            { to: '/docs/security-tiers', label: 'Security tiers' },
            { to: '/docs/plain-words', label: 'What these words mean' },
            { to: '/docs/backups', label: 'Backups and exports' },
            { to: '/docs/your-device', label: 'One device per account' },
          ],
        },
        // Support, Privacy and Terms are one group: the reader who wants any
        // of them wants "help and the legal bits", and three separate top-level
        // items for that crowded out the one that matters, Documentation.
        // It sits beside Documentation because both are places to read.
        {
          type: 'dropdown',
          label: 'Help',
          position: 'left',
          items: [
            { to: '/support', label: 'Support' },
            { to: '/privacy', label: 'Privacy Policy' },
            { to: '/terms', label: 'Terms of Service' },
          ],
        },
        // The only thing on this site a visitor can actually *do*, so it gets
        // a button treatment - see `.navbar-cta` in src/css/custom.css.
        {
          href: PLAY_STORE_URL,
          label: 'Get the app',
          position: 'right',
          className: 'navbar-cta',
          'aria-label': 'Get PasswordEpic on Google Play',
        },
        // Last of the configured items, which puts the globe immediately
        // before the colour-mode toggle Docusaurus appends after them. The two
        // belong together: both change how the page is presented to you rather
        // than what it says. `navbar-locale` reduces this to the globe alone on
        // desktop and puts a flag beside each language - see custom.css.
        {
          type: 'localeDropdown',
          position: 'right',
          className: 'navbar-locale',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Product',
          items: [
            { label: 'Get the app', href: PLAY_STORE_URL },
            { label: 'Overview', to: '/' },
            { label: 'How it works', to: '/docs/how-it-works' },
            { label: 'Security tiers', to: '/docs/security-tiers' },
            { label: 'The war for the vault', to: '/docs/attack-scenarios' },
            { label: 'What these words mean', to: '/docs/plain-words' },
          ],
        },
        {
          title: 'Guides',
          items: [
            { label: 'Your vault', to: '/docs/guide-vault' },
            { label: 'Generating passwords', to: '/docs/guide-generator' },
            { label: 'Settings', to: '/docs/guide-settings' },
            { label: 'Setting up autofill', to: '/docs/autofill' },
            { label: 'Your passcode', to: '/docs/your-passcode' },
            { label: 'Common problems', to: '/docs/faq' },
            { label: 'Backups and exports', to: '/docs/backups' },
            { label: 'One device per account', to: '/docs/your-device' },
          ],
        },
        {
          title: 'Legal',
          items: [
            { label: 'Privacy Policy', to: '/privacy' },
            { label: 'Terms of Service', to: '/terms' },
          ],
        },
        {
          title: 'Help',
          items: [
            { label: 'Support', to: '/support' },
            { label: 'support@passwordepic.com', href: 'mailto:support@passwordepic.com' },
          ],
        },
      ],
      copyright: `© ${new Date().getFullYear()} PasswordEpic`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
