import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** Autogenerated from the folder structure — add a .md file and it appears. */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
