/**
 * Values shared between the site config and the React components.
 *
 * The store URL deliberately omits the `&hl=` that Play's own share links
 * carry: that pins the listing to one language, and this site ships in two.
 * The QR in static/img/play-qr.svg encodes exactly this string, and is
 * regenerated by scripts/build-brand-assets.py - change one and rerun that.
 */
export const PLAY_STORE_URL =
  'https://play.google.com/store/apps/details?id=com.passwordepic.mobile';
